# Generated by Django 5.1.7 on 2025-03-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_catalogitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
