version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=download_you
      - DB_USER=postgres
      - DB_PASSWORD=111
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=video_download_queue
    networks:
      - app_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_worker
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=download_you
      - DB_USER=postgres
      - DB_PASSWORD=111
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=video_download_queue
    networks:
      - app_network
    command: ["python", "-m", "app.worker"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: download_you
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
